### PR TITLE
milestone1

### PR DESCRIPTION
**Pull request by Guy-Gustave**
the calculator pull-request for the first milestone

### CODE REVIEW

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

You have done a great job! I like your project. 

- You have a descriptive Readme
- Your Pull Request is nice. Good Job!
- You have deployed your website. Nice!!!
- You are using linters and no error is present. I am happy to see it. 
- Your code is clean.
**In short, I am very excited to see this project and proud of you. 👏** 

_There is always room to improve your code. Your project has met almost all the requirements but I would like to suggest some changes. I hope the next TSE who will review this project would be really impressed if you make those changes.  😄_ 

- [ ] App should be deployed on Heroku(or other hosts like Netfliy, Firebase, etc) and the live link is included in the README file. 
- [ ] [Optional] Please make your Pull Request more descriptive. 

Don't get discouraged. There are some students who make more mistakes than you do. We are here to learn. Everyone from Micrverse is here to help you. 

**GOOD LUCK!**

In case of any question please reach out to me n slack @arslanbisharat. 📞 

**Best,
Arslan Bisharat** 🅰️

**Comment by Guy-Gustave** [comment]
thank you for your suggestions. I changed my readme and add more description. I am grateful for your review

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hi @Guy-Gustave :hand: 
Awesome job implementing the requested changes
However, we still need to make some changes.

- [ ] The live version hosted at Heroku it seems to not work properly right now. I recommended you to use Netlify which has a better performance and it's way easier to use.
Screenshot from 2021-03-31 08-07-07

Happy coding :computer: 
**Sérgio Torres**

**Comment by Guy-Gustave** [comment]
than k for your interest in me. I fixed the errors

**Review by LamiaSristy — APPROVED** [review]
# Status: Approved. 🎉 🎉

Hello @Guy-Gustave, Fantastic work on this milestone. Therefore now your milestone is approved.

## The highlights: 
* The Live Demo is working.


Your milestone is now approved. Congratulations on your hard work. 🛠️ 

You can merge the branch now, good luck with your next milestone 🚀.

Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. Happy Coding 💻

**Pull request merged**
